# TODO

# On code change, pipeline needs to:
# - Run `maps.py`
# - Push changes to heroku (or other hosting solution)
# - Create new container image with relevant tag
# - Push container image to GHCR

# In addition, we need to be able to trigger the build for an arbitrary branch on demand


name: 'Build and Push Container Image'

#on:
#  push:
#    tags:
#      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

on:
  push:
    branches:
      - main

jobs:
  job_1:
    name: 'Generate Maps'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2
      - run: |
          pip install -r requirements.txt
          python maps.py
      - name: 'Build Container'
        id: build-image
        uses:  redhat-actions/buildah-build@v2
        with:
          image: dsei-app
          tags: latest ${{ github.sha }}
          dockerfiles: |
            ./Containerfile
      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/defencedigital
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
