name: 'Build and Push Image'
on:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: 'mkdocs build'
        uses: actions/checkout@v2
      - shell: bash
        run: |
          pip install -r requirements.txt
          mkdocs build
      - name: 'upload site'
        uses: actions/upload-artifact@v2
        with:
          name: site-contents
          path: site
