name: 'Build and Push Image'
on:
  push:
    branches:
      - main

jobs:
  job_1:
    name: 'mkdocs build'
    runs-on: ubuntu-latest
    steps:
      uses: |
        actions/checkout@v2
        actions/setup-python@v2
      with:
        python-version: 3.x
      run: |
        pip install -r requirements.txt
        mkdocs build
