name: 'Build and Push Image'
on:
  push:
    branches:
      - main

jobs:
  make-site:
    name: 'mkdocs build'
    runs-on: ubuntu-latest
    uses: actions/checkout@v2
    uses: actions/setup-python@v2
    steps:
      with:
        python-version: 3.x
      run: |
        pip install -r requirements.txt
        mkdocs build
